// <auto-generated />
namespace MovCustMVCAppWithAuthen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add3rowsinMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add3rowsinMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "202009071058035_Add 3 rows in Movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
